"""create core tables

Revision ID: 07d9603f80a6
Revises: 
Create Date: 2026-08-24 20:20:40.602484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d9603f80a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_chat_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('telethon_search', 'searxng', name='discoveryprovider'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'fetched', 'evaluated', 'approved', 'rejected', name='discoverystatus'), nullable=False),
    sa.Column('relevance_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_chat_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('monitored_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_chat_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('invite_link', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.Enum('sources_file', 'command', name='monitoredchatorigin'), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitored_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_chats_tg_chat_id'), ['tg_chat_id'], unique=True)

    op.create_table('portfolio_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('topics', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('html_url', sa.String(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name')
    )
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_text')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitored_chat_id', sa.Integer(), nullable=False),
    sa.Column('tg_message_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.Integer(), nullable=False),
    sa.Column('tg_username', sa.String(), nullable=True),
    sa.Column('tg_first_name', sa.String(), nullable=True),
    sa.Column('message_text', sa.String(), nullable=False),
    sa.Column('relevance_reason', sa.String(), nullable=False),
    sa.Column('found_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['monitored_chat_id'], ['monitored_chats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitored_chat_id', 'tg_message_id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_monitored_chat_id'), ['monitored_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_tg_user_id'), ['tg_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_leads_monitored_chat_id'))

    op.drop_table('leads')
    op.drop_table('search_queries')
    op.drop_table('portfolio_items')
    with op.batch_alter_table('monitored_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_chats_tg_chat_id'))

    op.drop_table('monitored_chats')
    op.drop_table('discovered_chats')
    # ### end Alembic commands ###
